"""
TrackingWorker — QThread wrapper around pluggable tracking strategies.

Responsibilities
----------------
- Unpack ReviewFrameItemViewModel dicts into plain TrackInput lists.
- Feed the chosen strategy engine frame-by-frame in chronological order.
- Repack TrackState results back into ReviewFrameItemViewModel, assigning
  persistent deterministic colors by UID.
- Store the final Layer C dict and expose it thread-safely.

Architectural contract
----------------------
- This module MAY import from presentation (view models) because it sits in
  the infrastructure layer and acts as the bridge between domain data and the
  math engine.
- The math engine (HungarianIoUTracker) must never be imported by UI code.
"""

from __future__ import annotations

import copy
from typing import Protocol

from PySide6.QtCore import QMutex, QMutexLocker, QThread, Signal

from app.infrastructure.video.hungarian_tracker import (
    HungarianIoUTracker,
    TrackInput,
    TrackState,
)
from app.presentation.view_models import ReviewFrameItemViewModel
from app.shared.logging_cfg import get_logger

logger = get_logger("Infrastructure->Tracking")

# ---------------------------------------------------------------------------
# Color utility — deterministic, persistent per UID
# ---------------------------------------------------------------------------

# A palette of visually distinct hues (HSV-spaced), pre-baked as hex strings.
# Generated by evenly spacing 20 hues around the color wheel, avoiding
# near-white / near-black and the magenta reserved for the DummyTracker.
_TRACK_PALETTE: list[str] = [
    "#e6194b", "#3cb44b", "#4363d8", "#f58231", "#42d4f4",
    "#f032e6", "#bfef45", "#fabed4", "#469990", "#dcbeff",
    "#9a6324", "#fffac8", "#800000", "#aaffc3", "#000075",
    "#a9a9a9", "#ffffff", "#ffe119", "#911eb4", "#ffd8b1",
]


def uid_to_color(uid: int) -> str:
    """
    Map a track UID to a persistent hex color string.

    Uses a fixed palette cycled by UID so that the same UID always gets
    the same color within a session, and colors are visually distinct for
    adjacent UIDs.
    """
    return _TRACK_PALETTE[(uid - 1) % len(_TRACK_PALETTE)]


# ---------------------------------------------------------------------------
# Strategy protocol (for future strategies: ByteTrack, DeepSORT, CSRT, …)
# ---------------------------------------------------------------------------

class TrackerStrategy(Protocol):
    """
    Minimal interface every tracking strategy must satisfy.

    The strategy receives the full source data dict and returns a completed
    Layer C dict.  Frame-by-frame progress reporting is handled by the
    concrete implementation or delegated to the worker.
    """

    def track(
            self,
            source_data: dict[int, list[ReviewFrameItemViewModel]],
    ) -> dict[int, list[ReviewFrameItemViewModel]]:
        ...


# ---------------------------------------------------------------------------
# DummyTracker — kept as a diagnostic / smoke-test strategy
# ---------------------------------------------------------------------------

class DummyTracker:
    """
    Diagnostic strategy: deep-copies source data and recolors boxes magenta.

    Use this to verify the full pipeline (worker lifecycle, signal wiring,
    Layer C population) without running any real math.
    """

    def track(
            self,
            source_data: dict[int, list[ReviewFrameItemViewModel]],
    ) -> dict[int, list[ReviewFrameItemViewModel]]:
        tracked_data: dict[int, list[ReviewFrameItemViewModel]] = {}

        for frame_idx, items in source_data.items():
            tracked_data[frame_idx] = []
            for item in items:
                new_item = copy.deepcopy(item)
                new_item.source = "Track (Dummy)"
                new_item.color_hex = "#ff00ff"
                new_item.item_key = f"track:{new_item.item_id}"
                tracked_data[frame_idx].append(new_item)

        return tracked_data


# ---------------------------------------------------------------------------
# HungarianStrategy — wraps the pure-Numpy math engine
# ---------------------------------------------------------------------------

class HungarianStrategy:
    """
    Production strategy: Hungarian IoU tracker with coast/decay memory.

    Iterates source frames in ascending order so the tracker sees them in
    the correct temporal sequence.
    """

    def __init__(
            self,
            iou_threshold: float = 0.3,
            confidence_decay: float = 0.05,
            min_confidence: float = 0.1,
    ) -> None:
        self._engine = HungarianIoUTracker(
            iou_threshold=iou_threshold,
            confidence_decay=confidence_decay,
            min_confidence=min_confidence,
        )

    def track(
            self,
            source_data: dict[int, list[ReviewFrameItemViewModel]],
    ) -> dict[int, list[ReviewFrameItemViewModel]]:
        self._engine.reset()
        tracked_data: dict[int, list[ReviewFrameItemViewModel]] = {}

        for frame_idx in sorted(source_data.keys()):
            raw_items = source_data[frame_idx]

            # Unpack view models → TrackInput
            detections: list[TrackInput] = [
                TrackInput(
                    bbox_xyxy=item.bbox_xyxy,
                    confidence=item.confidence if item.confidence is not None else 1.0,
                    label=item.label,
                )
                for item in raw_items
            ]

            # Run one frame through the math engine
            active_tracks: list[TrackState] = self._engine.update(detections)

            # Repack TrackState → ReviewFrameItemViewModel
            frame_items: list[ReviewFrameItemViewModel] = []
            for track in active_tracks:
                color = uid_to_color(track.uid)
                frame_items.append(
                    ReviewFrameItemViewModel(
                        item_id=f"track-{track.uid}",
                        source="Track (Hungarian)",
                        label=track.label,
                        bbox_xyxy=track.bbox_xyxy,
                        color_hex=color,
                        confidence=round(track.confidence, 4),
                        item_key=f"track:{track.uid}",
                    )
                )

            tracked_data[frame_idx] = frame_items

        return tracked_data


# ---------------------------------------------------------------------------
# TrackingWorker — QThread
# ---------------------------------------------------------------------------

_STRATEGY_MAP: dict[str, type] = {
    "dummy": DummyTracker,
    "hungarian": HungarianStrategy,
}


class TrackingWorker(QThread):
    progress_updated = Signal(int, int)  # (current_frame, total_frames)
    finished_processing = Signal()
    error_occurred = Signal(str)

    def __init__(
            self,
            strategy_name: str,
            source_data: dict[int, list[ReviewFrameItemViewModel]],
            parent=None,
    ) -> None:
        super().__init__(parent)
        self._strategy_name = strategy_name
        # Deep-copy source data so the worker owns a stable snapshot.
        self._source_data: dict[int, list[ReviewFrameItemViewModel]] = copy.deepcopy(source_data)
        self._tracked_data: dict[int, list[ReviewFrameItemViewModel]] = {}

        strategy_cls = _STRATEGY_MAP.get(strategy_name, DummyTracker)
        self._tracker: TrackerStrategy = strategy_cls()

        self._mutex = QMutex()
        self._stop_requested = False
        self._is_complete = False

        logger.info(
            "TrackingWorker initialized: strategy='{}', frames={}",
            strategy_name,
            len(source_data),
        )

    # ------------------------------------------------------------------
    # Public thread-safe API
    # ------------------------------------------------------------------

    def stop(self) -> None:
        self._stop_requested = True
        logger.info("TrackingWorker stop requested.")

    def is_complete(self) -> bool:
        return self._is_complete

    def get_tracked_data(self) -> dict[int, list[ReviewFrameItemViewModel]]:
        with QMutexLocker(self._mutex):
            return copy.deepcopy(self._tracked_data)

    # ------------------------------------------------------------------
    # QThread entry point
    # ------------------------------------------------------------------

    def run(self) -> None:
        logger.trace("TrackingWorker QThread started.")
        try:
            result = self._tracker.track(self._source_data)

            if self._stop_requested:
                logger.info("TrackingWorker stopped before writing results.")
                return

            with QMutexLocker(self._mutex):
                self._tracked_data = result

            total = len(result)
            self.progress_updated.emit(total, total)
            self._is_complete = True
            logger.info(
                "TrackingWorker completed. Tracked frames: {}",
                total,
            )

        except Exception as exc:
            logger.opt(exception=True).exception("TrackingWorker failed")
            self.error_occurred.emit(str(exc))

        finally:
            logger.trace("TrackingWorker QThread finishing.")
            self.finished_processing.emit()
